---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
return {
   bg = "#241c36",
   fg = "#eef4f6",
   selection = "#49376d",
   comment = "#8168b1",
   red = "#ec7979",
   orange = "#eca979",
   yellow = "#ece279",
   green = "#79ecb3",
   purple = "#a979ec",
   cyan = "#79ecec",
   pink = "#ec79d9",
   bright_red = "#ec7979",
   bright_green = "#8fefbf",
   bright_yellow = "#efe78f",
   bright_blue = "#b78fef",
   bright_magenta = "#ef8fcf",
   bright_cyan = "#9fefef",
   bright_white = "#f8fafc",
   menu = "#21222C",
   visual = "#3E4452",
   gutter_fg = "#4B5263",
   nontext = "#2e2343",
   white = "#ABB2BF",
   black = "#1b1528",
}
